### PR TITLE
Allow to recurse nested levels

### PR DESCRIPTION
**Pull request by nadirollo**
Maybe I'm getting something wrong, but I've been unable to recurse a complex tree from consul KV until I've fixed the recursion to not decode None values

### CODE REVIEW

**Comment by vdloo** [comment]
Hi @nadirollo, thanks! This is great. How do you feel about instead of ignoring the null values we instead represent them with None. See [this PR I made on your branch](https://github.com/nadirollo/consul-kv/pull/1). I also added a unit test to simulate getting a 'null' back from the API.

**Comment by nadirollo** [comment]
Hey @vdloo. That's great! 
It makes more sense to still present keys with None insted of ignoring them ;)

If you are happy with it and you are able to make a release including this... that would be amazing ;)

**Comment by nadirollo** [comment]
Merry XMas btw! :P

**Comment by nadirollo** [comment]
Hey @vdloo. I was testing with that implementation.

What's the benefit to represent the null values with None? 

I'm defining tree of values on the Consul KV and when using the library to get the dictionary out of it, I get this:
best_json_formatter_and_validator__advance_json_formatter_with_json_tools
 From a simple (but nested) structure on consul: 
consul_by_hashicorp

I'm not sure why the null is being received, but feels to me like a better idea not to decode it to None. Not sure if I'm missing something from the consul side... 
I think it would be a better idea to ignore them than to parse them to None :)

**Comment by vdloo** [comment]
Hi @Nadir, it looks like the keys come back as empty strings can be
ignored. In that case we should omit them yes. But I do think there is a
legit use for defining a key value pair 'some_value': null, that is
something else then there not being a key/value pair with key 'some_value'.

2016-12-28 17:41 GMT+01:00 Nadir <notifications@github.com>:

**Comment by nadirollo** [comment]
Hey!

Yeah, I think it's legit to have the use case where you can define some key/value pair with a null value. I was getting confused because of how I was initializing the consul KV... It makes sense to still parse the null values :)

Thanks for taking a look at it ;)

**Comment by vdloo** [comment]
How about this? https://github.com/vdloo/consul-kv/pull/11

**Comment by vdloo** [comment]
Cool, version 0.4 is now on pypy
```
$ pip install consul_kv
Collecting consul_kv
  Downloading consul_kv-0.4.tar.gz
```

**Pull request merged**
